name: CI

on:
  push:
    branches: [ "6" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/eebssk1/bbk/debian-bookworm:latest
      volumes:
        - /root:/user
    strategy:
      matrix:
        compiler: [llvm, gcc]
        target: [desktop, server_large, server_small, server_small_2]
    env:
      GZIP: -8

    steps:
      - uses: actions/checkout@v2
      - name: setup swap
        run: exec ./swap.sh
      - name: enable ccache
        uses: hendrikmuhs/ccache-action@v1.2.8
        with:
          verbose: 1
          max-size: "960M"
          key: ${{ matrix.target }}-${{ matrix.compiler }}
      - name: build
        run: ./b.sh ${{ matrix.target }} ${{ matrix.compiler }}
      - name: upload
        uses: actions/upload-artifact@v4
        with:
          name: debs_${{ matrix.target }}-${{ matrix.compiler }}
          path: "*.deb"
      - name: release
        uses: ncipollo/release-action@v1.14.0
        with:
          allowUpdates: true
          artifacts: "*.deb"
          commit: 6
          makeLatest: ${{ matrix.compiler == 'llvm' }}
          tag: ${{ env.VER }}-${{ matrix.compiler }}
