name: CI

on:
  push:
    branches: [ 6 ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/eebssk1/bbk/debian-bookworm:0.1

    steps:
      - uses: actions/checkout@v2
      - name: enable ccache
        uses: hendrikmuhs/ccache-action@v1.2.8
        with:
          verbose: 1
          max-size: "940M"
      - run: |
          curl -L "https://gitlab.com/xanmod/linux/-/archive/6.1.55-xanmod1.tar.bz2" | tar --bzip2 -xf -
          ./b.sh
      - uses: actions/upload-artifact@v2.2.4
        with:
          name: debs
          path: ./*.deb
